name: Node.js Build and Test

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests targeting 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run the job on an Ubuntu environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
        - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Set Node.js version to 18

      # Step 3: Install dependencies (including Mocha if needed)
